# Generated by Django 3.1.7 on 2021-05-01 05:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('blogad', models.CharField(max_length=100, verbose_name='Menü Adi')),
                ('baslik', models.CharField(max_length=100, verbose_name='Başlık')),
                ('icerik', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='içerik')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('durum', models.BooleanField(blank=True, null=True, verbose_name='Aktif')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='')),
                ('sira', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Egitim',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('altmenuadi', models.CharField(max_length=100, verbose_name='Menü Adi')),
                ('baslik', models.CharField(max_length=100, verbose_name='Başlık')),
                ('icerik', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='içerik')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('durum', models.BooleanField(blank=True, null=True, verbose_name='Aktif')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='')),
                ('sira', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ekip',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('adisoyadi', models.CharField(max_length=100, verbose_name='Adı Soyadı')),
                ('unvan', models.CharField(max_length=100, verbose_name='Ünvan')),
                ('icerik', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Öz Geçmiş')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Resim')),
                ('durum', models.BooleanField(blank=True, null=True, verbose_name='Aktif')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='')),
                ('sira', models.IntegerField(blank=True, verbose_name='Sıra')),
                ('tel', models.CharField(max_length=100, verbose_name='Telefon')),
                ('eposta', models.EmailField(max_length=254, verbose_name='e-posta')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineRandevu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('onlinetakvimid', models.IntegerField()),
                ('tarih', models.DateTimeField()),
                ('saat', models.DateTimeField()),
                ('adisoyadi', models.CharField(max_length=100, verbose_name='Adı Soyadı')),
                ('eposta', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OnlineTakvim',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tarih', models.DateTimeField()),
                ('saat', models.DateTimeField()),
                ('durum', models.BooleanField(blank=True, null=True, verbose_name='Aktif')),
            ],
            options={
                'ordering': ['tarih'],
            },
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('altmenuadi', models.CharField(max_length=100, verbose_name='Menü Adi')),
                ('baslik', models.CharField(max_length=100, verbose_name='Başlık')),
                ('icerik', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='içerik')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('durum', models.BooleanField(blank=True, null=True, verbose_name='Aktif')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='')),
                ('sira', models.PositiveSmallIntegerField(blank=True)),
            ],
        ),
    ]
