# Generated by Django 3.1.7 on 2021-05-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinetakvim',
            name='saat',
        ),
    ]
