# Generated by Django 3.1.7 on 2021-05-06 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_remove_onlinetakvim_saat'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='aciklama',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Açıklama'),
            preserve_default=False,
        ),
    ]
