# Generated by Django 3.1.7 on 2021-05-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_solutions_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='aciklama',
            field=models.CharField(blank=True, max_length=150, verbose_name='Açıklama'),
        ),
    ]
