# Generated by Django 3.1.7 on 2021-05-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20210506_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinetakvim',
            name='saat0',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinetakvim',
            name='saat1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinetakvim',
            name='saat2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinetakvim',
            name='saat3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinetakvim',
            name='saat4',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinetakvim',
            name='saat5',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinetakvim',
            name='saat6',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinetakvim',
            name='saat7',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
