# Generated by Django 3.1.7 on 2021-05-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20210506_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinerandevu',
            name='eposta',
            field=models.EmailField(max_length=254, verbose_name='e-posta'),
        ),
        migrations.AlterField(
            model_name='onlinerandevu',
            name='saat',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='onlinerandevu',
            name='tel',
            field=models.IntegerField(verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='onlinetakvim',
            name='saat0',
            field=models.TimeField(blank=True, null=True, verbose_name='1. Saat '),
        ),
    ]
