# Generated by Django 3.1.7 on 2021-05-08 11:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20210506_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuadi', models.CharField(max_length=100, verbose_name='Menu Adi')),
                ('ustmenuadi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bağlantı Yapılacak Menü Adı')),
                ('editor', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Sayfa İçeriği')),
                ('sira', models.IntegerField(blank=True, null=True, verbose_name='Alt Menu Sırası')),
            ],
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsoyad', models.CharField(max_length=100, verbose_name='Adı Soyadı')),
                ('tel', models.IntegerField(verbose_name='Telefon')),
                ('eposta', models.EmailField(max_length=254, verbose_name='E Posta')),
                ('adres', models.CharField(max_length=500, verbose_name='Adres')),
                ('kkno', models.IntegerField(verbose_name='Kredi Kartı Numarası')),
                ('kkad', models.CharField(max_length=100, verbose_name='Kredi Kartı Üzerinde ki Ad Soyad')),
                ('kksonkt', models.CharField(max_length=100, verbose_name='Son Kullanma Tarihi')),
                ('kkcvv', models.IntegerField(verbose_name='Güvenlik Kodu')),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('urunadi', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('urunfiyat', models.CharField(max_length=100, verbose_name='Ürün Fiyatı')),
                ('aciklama', models.CharField(max_length=500, verbose_name='Açıklama')),
            ],
        ),
        migrations.AlterField(
            model_name='solutions',
            name='aciklama',
            field=models.CharField(blank=True, max_length=500, verbose_name='Açıklama'),
        ),
    ]
