# Generated by Django 3.1.7 on 2021-05-09 11:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20210508_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='urunid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urun',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='urun',
            name='aciklama',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tanıtım'),
        ),
    ]
