# Generated by Django 3.1.7 on 2021-05-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20210509_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='menu',
            name='durum',
            field=models.BooleanField(blank=True, null=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='kkno',
            field=models.CharField(max_length=100, verbose_name='Kredi Kartı Numarası'),
        ),
    ]
