# Generated by Django 3.1.7 on 2021-06-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20210511_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNo', models.IntegerField(blank=True, null=True, verbose_name='Sıra Numarası')),
                ('adsoyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('eposta', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=100, verbose_name='Telefon Numarası')),
                ('konu', models.CharField(max_length=100, verbose_name='Konu')),
                ('mesaj', models.CharField(max_length=100, verbose_name='Mesaj')),
                ('olus_tarih', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsoyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('eposta', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=100, verbose_name='Telefon Numarası')),
                ('konu', models.CharField(max_length=100, verbose_name='Konu')),
                ('mesaj', models.CharField(max_length=100, verbose_name='Mesaj')),
                ('olus_tarih', models.DateTimeField()),
                ('durum', models.BooleanField(blank=True, null=True, verbose_name='Aktif')),
                ('onay', models.BooleanField(blank=True, null=True, verbose_name='Aktif')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Egitim',
        ),
    ]
